/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'contactInfo' : IDL.Text,
  'productId' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'shippingAddress' : IDL.Text,
  'buyerName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([Product], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'placeOrder' : IDL.Func([Order], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'contactInfo' : IDL.Text,
    'productId' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'shippingAddress' : IDL.Text,
    'buyerName' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([Product], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'placeOrder' : IDL.Func([Order], [], []),
  });
};

export const init = ({ IDL }) => { return []; };